# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - pgs  # optional, only if you want docs with this extra
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py
