# pyproject.toml

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "aoutools"
version = "0.1.0"
authors = [
  { name="Jaehyun Joo", email="jaehyunjoo@outlook.com" },
]
description = "A library of tools for analyzing All of Us data."
readme = "README.md"
requires-python = ">=3.8"
keywords = ["all-of-us", "genomics", "bioinformatics", "prs", "hail"]

# This field now points directly to your LICENSE file.
license = { file = "LICENSE" }

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
]
dependencies = [
    "hail",
    "pandas"
]

[project.urls]
Homepage = "https://github.com/dokyoonkimlab/aoutools"